name: unit-test
on:
  push:
    branches:
      - audit-rebased
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: `1.15.1`
      - name: Install dependencies
        run: docker-compose -f ./ops/docker-compose.yml build vault
        run: TAGS=unit ./ops/run_local_tests.sh
        run: docker-compose -f ./ops/docker-compose-db.yml down
        run: docker volume rm ops_vault-db



