name: integration-test
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout vault
        uses: actions/checkout@v2
        with:
          path: 'vault'        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideapp/ident
          path: 'ident'
          ref: integration
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}
      - name: Checkout integration test
        uses: actions/checkout@v2
        with:
          repository: provideapp/integration
          path: 'integration'
          ref: master
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}          
      - run: docker-compose -f ./ops/docker-compose-integration.yml up -d
        working-directory: vault
      - run:     make integration_vault                                    
        working-directory: integration       
      - run: docker-compose -f ./ops/docker-compose-integration.yml down
        working-directory: vault
      - run: docker volume rm ops_vault-db

